version: '3.8'

services:
  # ===============================
  # = MYSQL SERVICE CONFIGURATION
  # ===============================
  mysql:
    container_name: agrix-mysql
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root